baseurl = "https://docs.barricade.io/"
theme = "barricade"
description = "Resources for using and developing with Barricade"

publishdir = "static"

canonifyURLs = "true"
relativeURLs = "false"
pluralizeListTitles = "false"
plainIdAnchors = "true"

[params]
    title = "Barricade Docs"
    author = "Team Barricade"
    description = "Resources for using and developing with Barricade"

[[menu.main]]
    name = "Getting Started"
    url = "/getting-started/"
    identifier = "getting-started"
    weight = -100
[[menu.main]]
    name = "Using Barricade"
    url = "/using-barricade/"
    identifier = "using-barricade"
    weight = -80
[[menu.main]]
    name = "Security Guides"
    url = "/security-guide/"
    identifier = "security-guide"
    weight = -70
[[menu.main]]
    name = "Barricade API"
    url = "/api/"
    weight = -60
[[menu.main]]
    name = "Design Style Guide"
    url = "https://styleguide.barricade.io/"
    weight = -50
[[menu.main]]
    name = "Changelog"
    url = "/changelog/"
    identifier = "changelog"
    weight = -40



