baseurl = "https://docs.barricade.io/"
theme = "barricade"

publishdir = "static"
destination = "static"

canonifyURLs = "false"
relativeURLs = "false"
pluralizeListTitles = "false"
plainIdAnchors = "true"

[params]
    title = "Barricade Docs"
    author = "Team Barricade"

[[menu.main]]
    name = "Getting Started"
    url = "https://docs.barricade.io/getting-started/"
    identifier = "getting-started"
    weight = -100
[[menu.main]]
    name = "Using Barricade"
    url = "https://docs.barricade.io/using-barricade/"
    identifier = "using-barricade"
    weight = -80
[[menu.main]]
    name = "Security Guides"
    url = "https://docs.barricade.io/security-guide/"
    identifier = "security-guide"
    weight = -70
[[menu.main]]
    name = "Design Style Guide"
    url = "https://styleguide.barricade.io/"
    weight = -60
[[menu.main]]
    name = "Changelog"
    url = "https://docs.barricade.io/changelog/"
    identifier = "changelog"
    weight = -50
